# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['waveform_viewer.pyw'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # ── WebEngine（~50MB+，传感器波形分析完全用不到）──
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngine',
        'PySide6.QtWebEngineQuick',
        'PySide6.QtWebChannel',
        'PySide6.QtWebSockets',
        # ── Qt3D 全家桶（~15MB，无 3D 渲染需求）──
        'PySide6.Qt3DCore',
        'PySide6.Qt3DRender',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DExtras',
        # ── QtQuick / QML（~20MB，纯 Widgets 应用不需要）──
        'PySide6.QtQuick',
        'PySide6.QtQuickWidgets',
        'PySide6.QtQml',
        'PySide6.QtQmlModels',
        'PySide6.QtQmlWorkerScript',
        'PySide6.QtQuickControls2',
        'PySide6.QtQuickTemplates2',
        'PySide6.QtQuickTest',
        'PySide6.QtQuick3D',
        'PySide6.QtQuick3DRuntimeRender',
        'PySide6.QtQuick3DAssetImport',
        'PySide6.QtQuick3DUtils',
        # ── 多媒体（~8MB，无音视频播放）──
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtMultimediaQuick',
        # ── 硬件/外设（~5MB，只用 socket 做 TCP）──
        'PySide6.QtBluetooth',
        'PySide6.QtNfc',
        'PySide6.QtSensors',
        'PySide6.QtSerialPort',
        'PySide6.QtLocation',
        'PySide6.QtPositioning',
        # ── 其他确认用不到的模块 ──
        'PySide6.QtHelp',
        'PySide6.QtTextToSpeech',
        'PySide6.QtPdf',
        'PySide6.QtPdfWidgets',
        'PySide6.QtDesigner',
        'PySide6.QtRemoteObjects',
        'PySide6.QtScxml',
        'PySide6.QtAxContainer',
        'PySide6.QtDBus',
        'PySide6.QtDataVisualization',
        'PySide6.QtCharts',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='WaveScope',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='wavescope.ico',
)
